import Head from "next/head";
import Link from "next/link";
export default function PageLayaout({ children, title = "NewsApp" }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-between ml-8 mr-16">
        <div>
          <Link href={"/"}>CoriaJorge</Link>{" "}
        </div>
        <div>
          <Link href={"/About"}>About</Link>
        </div>
      </header>
      <main>{children}</main>
    </>
  );
}
